#!/usr/bin/env python3
import argparse, json
from ark_loot_bible.loot_quality import (
    configure_loot_source_quality,
    set_entry_item_multiplier,
    recalculate_loot_source_quality,
)

p = argparse.ArgumentParser()
p.add_argument("loot_source_id")
p.add_argument("loot_entry_id")
p.add_argument("minimum", type=float)
p.add_argument("maximum", type=float)
p.add_argument("item_multiplier", type=float)
p.add_argument("--color", default="RED")
p.add_argument("--ring", action="store_true")
p.add_argument("--level", type=int, default=60)
a = p.parse_args()

from ark_loot_bible.quality_engine import create_profile
profile_id = "QUALITY-CLI-DEMO"
create_profile(
    profile_id, "CLI_DEMO", "CLI Demonstration",
    a.minimum, a.maximum,
    verification_status="NEEDS_VERIFICATION",
    notes="Demonstration profile generated by CLI."
)
configure_loot_source_quality(a.loot_source_id, a.color, a.ring, a.level, profile_id)
set_entry_item_multiplier(a.loot_entry_id, a.item_multiplier)
print(json.dumps(recalculate_loot_source_quality(a.loot_source_id), indent=2))
